# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for runs with userManagedDependencies=False.

# Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: project_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.5.2 and later.
- python=3.7.9

- pip:
  - azureml-train-automl-runtime==1.38.1
  - inference-schema
  - azureml-interpret==1.38.0
  - azureml-defaults==1.38.0
- numpy==1.18.5
- pandas==1.1.5
- scikit-learn==0.22.1
- py-xgboost==1.3.3
- fbprophet==0.7.1
- holidays==0.10.3
- psutil==5.7.2
channels:
- anaconda
- conda-forge
